name: 'Setup aarch64-linux toolchain'
description: 'Setup the aarch64-linux toolchain'
inputs:
  location:
    required: false
    default: /tmp/toolchain
    description: "Installation path for the toolchain"

runs:
  using: "composite"
  steps:
  - name: Download and setup toolchain
    shell: bash
    run: |
      set -e
      mkdir -p "${{ inputs.location }}"
      curl -Ls https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu.tar.xz | tar -JC "${{ inputs.location }}" --strip-components=1 -x
      "${{ inputs.location }}/bin/aarch64-none-linux-gnu-gcc" -v
      export "ARM_TOOLS_PATH=${{ inputs.location }}" >> $GITHUB_ENV
      echo "${{ inputs.location }}/bin" >> $GITHUB_PATH
